// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zebxrobeiakodtouiiie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYnhyb2JlaWFrb2R0b3VpaWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzMzMjcsImV4cCI6MjA1ODY0OTMyN30.4zYT3c_ZnSCMADITTiGwjBFX-i1pObDIEFaA6ZKLZYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);